language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
addons:
  apt:
    sources:
      # add PPAs with more up-to-date toolchains
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-5
      - g++-5
      - clang-3.6
      - cmake
      - cmake-data
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - cd ../bin
  - ./Tests