env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ic5Y6qMA3z97kYeSpqpjkQvpm96IfD2Pq5B96hLMiqj18tmVP1Da/vi/B7JAFVXKa/kctptn7Eupq1U+J/bvUz3O1Q6E/RpWRx6vgSbjReiZ1kAF+EkxZh4+iB3sk4VAYgr2JjMKhn7HSul2/+e8dk4auPjBVRg0J/q6UgDkQVd5jIw6Ac3lYn8x6wsjKX/1b488Rv7BXcGxhsWxXdO7H9Jih45GuZ6c7oyzlWmkRT0i2rE/OgXIQtJXdlbQbpfela2kEYQAotI1Scy+KQPoCxKgvEYuXCFCeqNiZFdzdN5mNWowA8zFwu1X7XOyLpzEPXBeJJmcju/mKz+5n4zNjWBpntzKJIGpUI4Y9IbEZwAe3HSmuSPmBuoNxK9Y+thKDxnMO6Gl8wkywoPzCBI3/+ekggMvPkY6BZm/jy/bApFZVWNMlaaa9VMCTwqMveqhbd3oDGfhYAO0xmizYABfYzHb4BjYOAyWNkTeqVSxJqYn88RBg2fM3ku66C02/iwhGqdrwhBy3asZSIfjZ92mmn4c8wObXSCLDzbo6+Esc0vpSj9EbAe+3+gR4F1EEXIuzumkXHT1Z+v+GElc9XJrQcQGCSBP0EKEkzNO1a4FUEmfk2jT4jgHbOWVvAzbiJzXn/EPbhkENtqGFGjnCfXOsxcafHusuKNa6oOjtyx3gEc="

language: cpp

os:
  - linux

sudo: required

dist: trusty
  
compiler:
  - gcc
  - clang

before_install:
  # Coverity
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

  # GCC
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # Clang
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -y wget; fi
  - if [ "$CXX" == "clang++" ]; then wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -; fi
  - if [ "$CXX" == "clang++" ]; then sudo bash -c 'echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" >> /etc/apt/sources.list'; fi
  - if [ "$CXX" == "clang++" ]; then sudo bash -c 'echo "deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" >> /etc/apt/sources.list'; fi

  # CMake
  - sudo mkdir ~/cmake_tmp
  - cd ~/cmake_tmp
  - sudo wget http://cmake.org/files/v3.7/cmake-3.7.1-Linux-x86_64.tar.gz
  - sudo wget http://cmake.org/files/v3.7/cmake-3.7.1-Linux-x86_64.sh
  - sudo cmake-3.7.1-Linux-x86_64.sh --skip-license --prefix=/usr

  - sudo apt-get update
  - sudo apt-get install cmake

install:
  # GCC
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -y g++-6; fi
  - if [ "$CXX" == "g++" ]; then export CXX="g++-6"; fi

  # Clang
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -y clang++-3.9 libc++-dev; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.9"; fi

addons:
  coverity_scan:
    project:
      name: "danielil/Data-Structures-Algorithms"
    notification_email: daniel.s.iliescu@gmail.com
    build_command_prepend: "cmake ."
    build_command: "make"
    branch_pattern: coverity_scan

script:
  - cmake .
  - make
  - ctest --verbose

after_success:
  - bash <(curl -s https://codecov.io/bash)